### ISSUE TITLE
[Crash] Passing `--image` crashes if no `GraphViz` is installed

### ISSUE THREAD

**Issue by esttorhe** [segiddins/cocoapods-dependencies#11]
### Command

```
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/bin/pod dependencies --image
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.1 (7B85)
         Git : git version 2.6.1
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 4644e8e8e23af4fc397e7b5d0f6f7d7282571a9f
               master - https://github.com/CocoaPods/Specs.git @ 0d45cdeb25966d1fe57628c7157f18e159995db4
```

### Plugins

```
cocoapods-deintegrate    : 0.2.1
cocoapods-dependencies   : 0.5.0
cocoapods-keys           : 1.5.2
cocoapods-no-dev-schemes : 1.0.0
cocoapods-plugins        : 0.4.2
cocoapods-search         : 0.1.0
cocoapods-stats          : 0.6.2
cocoapods-trunk          : 0.6.4
cocoapods-try            : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

plugin "cocoapods-no-dev-schemes"

pod 'KVOController'
pod 'CocoaAsyncSocket'
pod 'LoremIpsum'
pod 'SDWebImage'
pod 'PulsingHalo'
pod 'MONActivityIndicatorView'
pod 'RESideMenu'
pod 'ISO8601DateFormatter'
pod 'NSString-ZENInflections'
# pod 'SwiftCoAP', path: "/work/personal/SwiftCoAP"
pod 'HockeySDK'
pod 'Spark-SDK'
pod 'SparkSetup/Comm', '~> 0.3.2'

# Swift
pod 'BRYXBanner', '~> 0.4.1'
pod 'SwiftyUserDefaults'
pod 'Dollar', '~> 4.0.1'
pod 'Cent', '~> 4.0.1'
pod 'KeychainAccess', '~> 2.0.0'
pod 'Alamofire', '~>2.0'
pod 'Cartography'
pod 'SwiftyJSON', '~>2.3.0'
pod 'OAuthToo', git: "git@github.com:kierangraham/OAuthToo.git", branch: "swift2"
#pod 'OAuthToo', path: "/work/personal/OAuthToo"
pod 'SwiftCoAP', git: "git@github.com:kierangraham/SwiftCoAP.git", branch: "cocoapods-swift2"
pod 'Async', :git => "https://github.com/duemunk/Async.git", branch: "feature/Swift_2.0"
pod 'RxSwift', '~> 2.0.0-alpha.3'
pod 'RxCocoa', '~> 2.0.0-alpha.3'
pod 'RxViewModel', '~> 2.1.1'
pod 'ReachabilitySwift'

plugin 'cocoapods-keys', {
  :project => "Brewbot",
  :keys => [
    "HockeyProductionSecret",
    "HockeyBetaSecret",

    "BrewbotProductionOAuthClientID",
    "BrewbotProductionOAuthClientSecret",

    "BrewbotStagingOAuthClientID",
    "BrewbotStagingOAuthClientSecret",

    "BrewbotDevelopmentOAuthClientID",
    "BrewbotDevelopmentOAuthClientSecret",

    "ParticleCloudUsername",
    "ParticleCloudPassword",

    "PhotonID"
]}

target :BrewbotTests do
    pod 'Quick', '~> 0.6.0'
    pod 'Nimble', '2.0.0'
    pod 'FBSnapshotTestCase', :git => "git@github.com:esttorhe/ios-snapshot-test-case.git"
    pod 'Nimble-Snapshots', :git => "git@github.com:esttorhe/Nimble-Snapshots.git"
end
```

### Error

```
StandardError - GraphViz not installed or dot not in PATH. Install GraphViz or use the 'path' option
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:544:in `output'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/cocoapods-dependencies-0.5.0/lib/pod/command/dependencies.rb:164:in `graphviz_image_output'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/cocoapods-dependencies-0.5.0/lib/pod/command/dependencies.rb:53:in `run'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/bin/pod:23:in `load'
/Users/creegan/Documents/Code/Brewbot/brewbot-ios/vendor/ruby/2.2.0/bin/pod:23:in `<main>'
```

---

Don't know if `GraphViz` is required anyways but is not implied in the instructions; thought that passing `--image` would not required `GraphViz` given that there's a `--graphviz` option.

**Comment by segiddins** [comment]
Nah, graphviz is required since it's what makes the image. I'll make that a nicer error though and clarify the docs.

**Comment by esttorhe** [comment]
:ok_hand: makes sense now.

Thanks :bow: 

Closing this now since this is not an issue :no_entry:

**Comment by segiddins** [comment]
Done in 0.5.1!

**Comment by esttorhe** [comment]
:clap:
